{{- if eq .Values.workload.kind "Deployment" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "rhdh.fullname" . }}
  labels:
    {{- include "rhdh.labels" . | nindent 4 }}
  {{- if or .Values.commonAnnotations .Values.deploymentAnnotations }}
  annotations:
    {{- with .Values.commonAnnotations }}
    {{- include "common.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}
    {{- end }}
    {{- with .Values.deploymentAnnotations }}
    {{- include "common.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  revisionHistoryLimit: {{ .Values.revisionHistoryLimit }}
  {{- with .Values.strategy }}
  strategy:
    {{- include "common.tplvalues.render" (dict "value" . "context" $) | nindent 4 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "rhdh.selectorLabels" . | nindent 6 }}
  template:
    {{- include "rhdh.backstagePodTemplate" . | nindent 4 }}
{{- end }}