{{- if .Values.podDisruptionBudget.create }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "rhdh.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "rhdh.labels" . | nindent 4 }}
    app.kubernetes.io/component: backstage
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.podDisruptionBudget.minAvailable }}
  minAvailable: {{ . }}
  {{- end }}
  {{- with .Values.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ . }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "rhdh.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: backstage
{{- end }}
