{{- if and .Values.auth.backend.enabled (not .Values.auth.backend.existingSecretRef.name) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rhdh.backend-secret-name" . }}
  labels:
    {{- include "rhdh.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  {{ include "rhdh.backend-secret-key" . }}: {{ (ternary (randAlphaNum 24) .Values.auth.backend.value (empty .Values.auth.backend.value)) | b64enc | quote }}
{{- end }}
