{{- if and (not .Values.auth.backend.existingSecret) .Values.auth.backend.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rhdh.backend-secret-name" . }}
  labels:
    {{- include "rhdh.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
data:
  backend-secret: {{ (ternary (randAlphaNum 24) .Values.auth.backend.value (empty .Values.auth.backend.value)) | b64enc | quote }}
{{- end }}
