{{- if and .Values.serverlessOperator.enabled (eq (include "olm-version" .) "v0") }}
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: serverless-operator-group
  namespace: {{ .Values.serverlessOperator.subscription.namespace }}
spec: {}
{{- end }}
