{{- if and .Values.serverlessLogicOperator.enabled .Values.serverlessLogicOperator.createNamespace (ne .Values.serverlessLogicOperator.subscription.namespace .Values.serverlessOperator.subscription.namespace) }}
---
apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Values.serverlessLogicOperator.subscription.namespace }}
  annotations:
    "helm.sh/resource-policy": keep
{{- end }}
