{{- $packageName := .Values.serverlessLogicOperator.subscription.spec.name -}}
{{- $subscriptionNamespace := .Values.serverlessLogicOperator.subscription.namespace -}}
{{- if and (eq (include "olm-version" .) "v0") .Values.serverlessLogicOperator.enabled }}
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: {{ $packageName }}
  namespace: {{ $subscriptionNamespace }}
spec:
  {{- toYaml .Values.serverlessLogicOperator.subscription.spec | nindent 2 }}
{{- end }}
