# Workaround for kind cluster in CI which has no Routes and no PVCs
route:
  enabled: false

lightspeed:
  sidecar:
    env:
      - name: SERVICE_HOST
        value: "0.0.0.0"

postgresql:
  primary:
    persistence:
      enabled: false
