postgresql:
  enabled: false
externalDatabase:
  host: "ext-db-postgresql.ext-services.svc.cluster.local"
  port: 5432
  user: "postgres"
  existingSecretRef:
    name: "ext-db-password"
    key: "password"
test:
  enabled: false
openshift:
  route:
    enabled: false
