postgresql:
  enabled: false
externalDatabase:
  host: "db.example.com"
  port: 5432
  user: "rhdh"
  existingSecretRef:
    name: "my-db-secret"
    key: "db-password"
test:
  enabled: false
openshift:
  route:
    enabled: false
