extraAppConfig:
  - configMapRef: "my-app-config"
    filename: "app-config-custom.yaml"
lightspeed:
  existingSecret: "test-lightspeed-secret"
  config:
    stack:
      existingConfigMap:
        name: "test-lightspeed-stack"
    server:
      existingConfigMap:
        name: "test-lightspeed-server"
    profile:
      existingConfigMap:
        name: "test-lightspeed-profile"
  core:
    extraEnv:
      - name: SERVICE_HOST
        value: "0.0.0.0"
orchestrator:
  enabled: true
