lightspeed:
  enabled: true
  existingSecret: "test-lightspeed-secret"
  config:
    stack:
      existingConfigMap:
        name: "test-lightspeed-stack"
    server:
      existingConfigMap:
        name: "test-lightspeed-server"
    profile:
      existingConfigMap:
        name: "test-lightspeed-profile"

test:
  injectTestLightspeedResources: true
