route:
  enabled: false

postgresql:
  primary:
    persistence:
      enabled: false

dynamicPlugins:
  plugins:
    # Enable additional plugins, which should be merged with the Orchestrator plugins
    - package: ./dynamic-plugins/dist/red-hat-developer-hub-backstage-plugin-bulk-import-backend-dynamic
      enabled: true
    - package: ./dynamic-plugins/dist/red-hat-developer-hub-backstage-plugin-bulk-import
      enabled: true

orchestrator:
  enabled: true
