{{- if .Values.dataRetriever.enabled -}}
apiVersion: v1
kind: Pod
metadata:
  name: {{ include "rhdh-must-gather.dataRetrieverName" . }}
  labels:
    {{- include "rhdh-must-gather.labels" . | nindent 4 }}
    app.kubernetes.io/component: data-retriever
spec:
  automountServiceAccountToken: false
  restartPolicy: Never
  {{- with .Values.imagePullSecrets }}
  imagePullSecrets:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.podSecurityContext }}
  securityContext:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchLabels:
              {{- include "rhdh-must-gather.selectorLabels" . | nindent 14 }}
              app.kubernetes.io/component: gather
          topologyKey: kubernetes.io/hostname
  containers:
    - name: data-retriever
      {{- $drImage := deepCopy .Values.image }}
      {{- if .Values.dataRetriever.image.registry }}{{ $_ := set $drImage "registry" .Values.dataRetriever.image.registry }}{{- end }}
      {{- if .Values.dataRetriever.image.repository }}{{ $_ := set $drImage "repository" .Values.dataRetriever.image.repository }}{{- end }}
      {{- if .Values.dataRetriever.image.tag }}{{ $_ := set $drImage "tag" .Values.dataRetriever.image.tag }}{{- end }}
      {{- if .Values.dataRetriever.image.digest }}{{ $_ := set $drImage "digest" .Values.dataRetriever.image.digest }}{{- end }}
      image: {{ include "rhdh-must-gather.image" (dict "image" $drImage "defaultTag" .Chart.AppVersion) | quote }} # NOSONAR
      imagePullPolicy: {{ .Values.dataRetriever.image.pullPolicy | default .Values.image.pullPolicy | default "IfNotPresent" }}
      {{- with .Values.securityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      command:
        - sleep
        - infinity
      volumeMounts:
        - name: must-gather-output
          mountPath: /data
          readOnly: true
      {{- with .Values.dataRetriever.resources }}
      resources:
        {{- toYaml . | nindent 8 }}
      {{- end }}
  volumes:
    - name: must-gather-output
      persistentVolumeClaim:
        claimName: {{ include "rhdh-must-gather.fullname" . }}-pvc
  {{- with .Values.nodeSelector }}
  nodeSelector:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.tolerations }}
  tolerations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
