apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "rhdh-must-gather.serviceAccountName" . }}
  labels:
    {{- include "rhdh-must-gather.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: false
