{{- $lightspeed := include "rhdh.lightspeed" . | fromYaml -}}
{{- if and $lightspeed.enabled $lightspeed.secret.create }}
{{- $stringData := include "rhdh.lightspeed.secretStringData" (dict "context" . "lightspeed" $lightspeed) | fromYaml -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "rhdh.lightspeed.secretName" (dict "context" . "lightspeed" $lightspeed) }}
  labels:
    {{- include "rhdh.labels" . | nindent 4 }}
  {{- with .Values.commonAnnotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
type: Opaque
stringData:
{{- range $key, $value := $stringData }}
  {{ $key }}: |-
{{ $value | nindent 4 }}
{{- end }}
{{- end }}
