# Workaround for kind cluster in CI which has no Routes and no PVCs
route:
  enabled: false

global:
  # CI: skip dynamic plugin downloads to speed up tests.
  dynamic:
    includes: []
  # FIXME(RHIDP-15458): remove plugins override once next catalog index is stable with correct lightspeed refs in the DPDY
  lightspeed:
    plugins: []
    sidecar:
      env:
        - name: SERVICE_HOST
          value: "0.0.0.0"

upstream:
  postgresql:
    primary:
      persistence:
        enabled: false
