name: Test Charts

on:
  pull_request:
    branches:
      - main
      - release-1.[0-9]+

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number }}
  cancel-in-progress: true

jobs:

  test-chart:
    # Aligning job name with the OpenShift CI config: https://github.com/openshift/release/blob/master/core-services/prow/02_config/redhat-developer/rhdh-chart/_prowconfig.yaml#L18
    name: Test Latest Release
    runs-on: ubuntu-latest
    timeout-minutes: 120

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0

      - name: Generate full-plugins values for template sanity check
        run: |
          yq e '{"global": {"dynamic": {"includes": .global.dynamic.includes}, "lightspeed": {"plugins": .global.lightspeed.plugins}}, "orchestrator": {"plugins": .orchestrator.plugins}}' \
            charts/backstage/values.yaml > /tmp/backstage-full-plugins-values.yaml

      - name: Test charts
        uses: ./.github/actions/test-charts
        with:
          target_branch: ${{ github.event.pull_request.base.ref }}
          helm_template_values_file: /tmp/backstage-full-plugins-values.yaml
