name: PR TOML Validator

on:
  push:
    paths:
      - '**.toml'
      - '.github/workflows/toml-checks.yaml'
  pull_request:
    paths:
      - '**.toml'
      - '.github/workflows/toml-checks.yaml'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - uses: tombi-toml/setup-tombi@74c3f4f31e7915e27c3397831e4c628463e3e0da # v1.1.1
        with:
          version: 'v0.9.9'
          checksum: 'b50dbc90ec27591dbaf564b628bd3b3e4ead371a60931bc8ea5f34d7cd1d3607'
      - name: Validate TOML files
        run: tombi lint
